CPMAddPackage("gh:xtensor-stack/xtl#0.7.2")
CPMAddPackage("gh:xtensor-stack/xtensor#0.23.10")
if(xtensor_ADDED)
  message(STATUS "Found xtensor: ${xtensor_SOURCE_DIR}")
  include_directories(${xtensor_SOURCE_DIR}/include)
endif(xtensor_ADDED)
